### ISSUE TITLE
How to cache i18n json files?

### ISSUE THREAD

**Issue by asgeo1** [nolazybits/angular-i18n#1]
Hey there,

I'm interested in using this. But I'm not keen for it to make an XHR request to retrieve the localization file though, as I'm building a mobile/cordova app.

I'm using RequireJS and Grunt to create my production build .js file. If my build process appends the correct localisation file (say, en-US.js), is there a way we could have this refer to that file?

I'm thinking the same way https://github.com/ericclemmons/grunt-angular-templates can bundle templates directly into the $templateCache, so the template thing in Angular will fetch from the cache rather than making the XHR request.

What do you think? I'm pretty new to AngularJS and don't know the best way to do things.

**Comment by nolazybits** [comment]
I know it's a year old but the new version of the library as now 2 methods that could help you with this
https://github.com/nolazybits/angular-i18n#language-1


| Methods | Description |    
| :-------| ----------- |    
| [addTranslationObject(lang, json, section)](#addtranslationobject) | add a translation object directly to i18n |
| [removeTranslationObject(lang, section)](#removetranslationobject) | remove a translation object added or loaded to the library |

##### addTranslationObject(lang: string, json: string, section: string)
> add a translation directly to the library.
> lang: the language to add
> json: the json string
> (section): the section for the language file

This can prove usefull if you want to retrieve the translation object(s) yourself and then add them to this library.

##### removeTranslationObject(lang: string, section: string)
> remove a translation from the library
> lang: the language to remove from
> (section): the section to remove from
