### ISSUE TITLE
Default values for `allowPartialFileLoading` and `fileURL` conflict

### ISSUE THREAD

**Issue by ramirezd42** [nolazybits/angular-i18n#17]
The default configuration for this module looks for files of the format *"/i18n/|LANG|_|PART|.json"*.

Since **allowPartialFileLoading** is disabled by default, it looks for a file named *"/i18n/en-US_|PART|.json"* which seems silly to me. 

I propose setting the default value for **fileURL** to be *'/i18n/|LANG|.json'*. Looking at the readme definition for the fileURL option, it looks like this used to be the default.

I'd be happy to submit a PR. let me know what you think!

**Comment by nolazybits** [comment]
Hello ramirez, 

Thanks for reporting this.
Please if you can send a PR that would be great :+1:

**Comment by nolazybits** [comment]
Fixed in eaea8fcda0a2ee60924a08589031f1500ceea021
